# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9196fed71c88e7bd2c777c2c37b2a1c697d913f6c097e6c470134225f14d637dcf1cfc26a6c8246437bc5f9d9d63a20bc09de43c7415d06aade1bdb7a69234e9

test:
  secret_key_base: a1f7566b5fe4f85c6fe64c90577039cc422ea318c6bfef8c661c1f8ae9588f7140344a875562bed1b39aa98d23940a2ac117e348c063adf9e5d56fcf9ac16a7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
